# Generated by Django 4.0.1 on 2024-04-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctor_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='qualification',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
