# Generated by Django 4.0.1 on 2024-04-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_staff_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='qualification',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
