# Generated by Django 4.0.1 on 2024-04-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_salary_year_salary_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='total',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
