# Generated by Django 4.0.1 on 2024-04-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentpackage_booking',
            name='total',
        ),
        migrations.AddField(
            model_name='treatmentpackage_booking',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
