
from django.contrib import admin
from django.urls import path

from myapp import views

urlpatterns = [
    path('login/', views.login),
    path('loginpost/', views.loginpost),
    path('logout/', views.logout),
    path('admin_home/', views.admin_home),
    path('admin_doctoradd/', views.admin_doctoradd),
    path('admin_adddoctor_post/', views.admin_adddoctor_post),
    path('admin_viewdoctors/', views.admin_viewdoctors),
    path('admin_viewdoctorspost/', views.admin_viewdoctorspost),
    path('admin_doctoredit/<id>', views.admin_doctoredit),
    path('admin_editdoctor_post/', views.admin_editdoctor_post),
    path('admin_delete_Doctor/<id>', views.admin_delete_Doctor),
    path('admin_Addsalary/<id>', views.admin_Addsalary),
    path('admin_Addsalarypost/', views.admin_Addsalarypost),
    path('adminviewsalary/<id>', views.adminviewsalary),
    path('adminviewsalarypost/', views.adminviewsalarypost),
    path('admindelete_salary/<id>', views.admindelete_salary),
    path('admin_viewcomplaint/', views.admin_viewcomplaint),
    path('admin_viewcomplaintpost/', views.admin_viewcomplaintpost),
    path('admin_sendreply/<id>', views.admin_sendreply),
    path('admin_sendreplypost/', views.admin_sendreplypost),
    path('admin_add_staff/', views.admin_add_staff),
    path('admin_add_staff_post/', views.admin_add_staff_post),
    path('admin_viewstaff/', views.admin_viewstaff),
    path('admin_viewstaffpost/', views.admin_viewstaffpost),
    path('admin_staffedit/<id>', views.admin_staffedit),
    path('admin_editstaff_post/', views.admin_editstaff_post),
    path('admin_delete_staff/<id>', views.admin_delete_staff),



    path('admin_add_therapist/', views.admin_add_therapist),
    path('admin_add_therapist_post/', views.admin_add_therapist_post),
    path('admin_viewtherapist/', views.admin_viewtherapist),
    path('admin_viewtherapistpost/', views.admin_viewtherapistpost),
    path('admin_therapistedit/<id>', views.admin_therapistedit),
    path('admin_edittherapist_post/', views.admin_edittherapist_post),
    path('admin_delete_therapist/<id>', views.admin_delete_therapist),
    path('admin_Doctorviewschedule/', views.admin_Doctorviewschedule),
    path('admin_Doctorviewschedulepost/', views.admin_Doctorviewschedulepost),
    path('admin_viewregisterduser/', views.admin_viewregisterduser),
    path('admin_viewregisterduserpost/', views.admin_viewregisterduserpost),
    path('admin_viewdoctorbooking/', views.admin_viewdoctorbooking),
    path('admin_viewdoctorbookingpost/', views.admin_viewdoctorbookingpost),
    path('admin_viewservicebookingreports/', views.admin_viewservicebookingreports),
    path('admin_viewservicebookingreports_post/', views.admin_viewservicebookingreports_post),
    path('admin_viewreviews/', views.admin_viewreviews),
    path('admin_viewreviews_post/', views.admin_viewreviews_post),
    path('admin_viewappfeedback/', views.admin_viewappfeedback),
    path('admin_viewappfeedback_post/', views.admin_viewappfeedback_post),
    path('admin_viewpaymentdoc_reports/', views.admin_viewpaymentdoc_reports),
    path('admin_viewpaymentdoc_reports_post/', views.admin_viewpaymentdoc_reports_post),
    path('admin_viewpaymentpack_reports/', views.admin_viewpaymentpack_reports),
    path('admin_viewpaymentpack_reports_post/', views.admin_viewpaymentpack_reports_post),
    path('admin_viewpaymentserv_reports/', views.admin_viewpaymentserv_reports),
    path('admin_viewpaymentserv_reports_post/', views.admin_viewpaymentserv_reports_post),
    path('admin_viewmedicinestock/', views.admin_viewmedicinestock),
    path('admin_viewmedicinestock_post/', views.admin_viewmedicinestock_post),

    ########doctor
    path('doctor_home/', views.doctor_home),
    path('doctor_viewprofile/', views.doctor_viewprofile),
    path('doctor_changepassword/', views.doctor_changepassword),
    path('doctor_changepasswordpost/', views.doctor_changepasswordpost),
    path('doctor_Addschedule/', views.doctor_Addschedule),
    path('doctor_Addschedulepost/', views.doctor_Addschedulepost),
    path('doctor_Doctorviewschedule/', views.doctor_Doctorviewschedule),
    path('doctor_Doctorviewschedulepost/', views.doctor_Doctorviewschedulepost),
    path('doctor_Doctordelete_schedule/<id>', views.doctor_Doctordelete_schedule),
    path('doctor_editschedule/<id>', views.doctor_editschedule),
    path('doctor_editschedulepost/', views.doctor_editschedulepost),
    path('doctor_viewdoctorbookingappoinment/<id>', views.doctor_viewdoctorbookingappoinment),
    path('doctor_viewdoctorbookingappoinment_post/', views.doctor_viewdoctorbookingappoinment_post),
    path('doctor_addprescription/<id>', views.doctor_addprescription),
    path('doctor_addprescriptionppost/', views.doctor_addprescriptionppost),
    path('doctor_viewprescription/<id>', views.doctor_viewprescription),
    path('doctor_assign_therapist/<id>', views.doctor_assign_therapist),
    path('doctor_assign_therapist_post/', views.doctor_assign_therapist_post),
    path('doctor_viewassigned_therapist/<id>', views.doctor_viewassigned_therapist),
    path('dovtor_viewsalary/', views.dovtor_viewsalary),
    path('doctorviewsalarypost/', views.doctorviewsalarypost),

    ###############therapist
    path('therapist_home/', views.therapist_home),
    path('therapist_viewprofile/', views.therapist_viewprofile),
    path('therapist_changepassword/', views.therapist_changepassword),
    path('therapist_changepasswordpost/', views.therapist_changepasswordpost),
    path('therapist_viewassigneduser/', views.therapist_viewassigneduser),
    path('therapist_viewassigneduser_post/', views.therapist_viewassigneduser_post),

    # path('therapist_viewreviews/', views.therapist_viewreviews),
    # path('therapist_viewreviews_post/', views.therapist_viewreviews_post),
    path('therapist_viewsalary/', views.therapist_viewsalary),
    path('therapistviewsalarypost/', views.therapistviewsalarypost),
    path('therapist_addprescription/<id>', views.therapist_addprescription),
    path('therapist_addprescriptionppost/', views.therapist_addprescriptionppost),
    path('therapist_viewprescription/<id>', views.therapist_viewprescription),

    ##############staff
    path('staff_home/', views.staff_home),
    path('staff_viewprofile/', views.staff_viewprofile),
    path('staff_viewsalary/', views.staff_viewsalary),
    path('staffviewsalarypost/', views.staffviewsalarypost),
    path('staff_changepassword/', views.staff_changepassword),
    path('staff_changepasswordpost/', views.staff_changepasswordpost),

    path('staff_viewbooking/', views.staff_viewbooking),
    path('staff_viewbookingpost/', views.staff_viewbookingpost),
    path('staff_approvebooking/<id>', views.staff_approvebooking),
    path('staff_rejectbooking/<id>', views.staff_rejectbooking),
    path('staff_viewapprovedbooking/', views.staff_viewapprovedbooking),
    path('staff_viewapprovedbookingpost/', views.staff_viewapprovedbookingpost),
    path('staff_viewrejectedbooking/', views.staff_viewrejectedbooking),
    path('staff_viewrejectedbookingpost/', views.staff_viewrejectedbookingpost),
    path('staff_reschedule/', views.staff_reschedule),
    path('staff_reschedulepost/', views.staff_reschedulepost),
    path('staff_viewpatientsmedicalhistoryreports/', views.staff_viewpatientsmedicalhistoryreports),
    path('staff_viewpatientsmedicalhistoryreports_post/', views.staff_viewpatientsmedicalhistoryreports_post),
    # path('staff_viewmedicine_entry/', views.staff_viewmedicine_entry),
    # path('staff_viewmedicine_entrypost/', views.staff_viewmedicine_entrypost),
    path('staff_viewservicebooking/', views.staff_viewservicebooking),
    path('staff_viewservicebookingpost/', views.staff_viewservicebookingpost),
    path('staff_viewapprovedservicebooking/', views.staff_viewapprovedservicebooking),
    path('staff_viewapprovedservicebookingpost/', views.staff_viewapprovedservicebookingpost),
    path('staff_viewrejectedservicebooking/', views.staff_viewrejectedservicebooking),
    path('staff_viewtpbooking/', views.staff_viewtpbooking),
    path('staff_viewtpbookingpost/', views.staff_viewtpbookingpost),
    path('staff_viewapprovetpbooking/', views.staff_viewapprovetpbooking),
    path('staff_viewapprovedtpbookingpost/', views.staff_viewapprovedtpbookingpost),
    path('staff_viewrejectedtpbooking/', views.staff_viewrejectedtpbooking),
    path('staff_viewrejectedtpbookingpost/', views.staff_viewrejectedtpbookingpost),
    path('staff_approvetpbooking/<id>', views.staff_approvetpbooking),
    path('staff_rejecttpbooking/<id>', views.staff_rejecttpbooking),
    path('staff_approveservicebooking/<id>', views.staff_approveservicebooking),
    path('staff_rejectservicebooking/<id>', views.staff_rejectservicebooking),
    # path('View_therapist_booking_entryfor_patients/', views.View_therapist_booking_entryfor_patients),
    # path('View_therapist_booking_entryfor_patients_post/', views.View_therapist_booking_entryfor_patients_post),
    path('staff_addtreatmentpackages/', views.staff_addtreatmentpackages),
    path('staff_addtreatmentpackages_post/', views.staff_addtreatmentpackages_post),
    path('staff_View_treatmentpackages/', views.staff_View_treatmentpackages),
    path('staff_View_treatmentpackages_post/', views.staff_View_treatmentpackages_post),
    path('staff_edit_treatmentpackages/<id>', views.staff_edit_treatmentpackages),
    path('staff_edit_treatmentpackages_post/', views.staff_edit_treatmentpackages_post),
    path('staff_delete_treatmentpackages/<id>', views.staff_delete_treatmentpackages),
    path('staff_addmedicine_entry/', views.staff_addmedicine_entry),
    path('staff_addmedicine_entry_post/', views.staff_addmedicine_entry_post),
    path('staff_deletemedicine_entry/<id>', views.staff_deletemedicine_entry),
    path('staff_editmedicine/<id>', views.staff_editmedicine),
    path('staff_editmedicineentypost/', views.staff_editmedicineentypost),
    path('staff_viewmedicine_entry/', views.staff_viewmedicine_entry),
    path('staff_viewmedicine_entrypost/', views.staff_viewmedicine_entrypost),
    path('staff_addService_entry/', views.staff_addService_entry),
    path('staff_addService_entry_post/', views.staff_addService_entry_post),
    path('staff_deleteService_entry/<id>', views.staff_deleteService_entry),
    path('staff_editService_entry/<id>', views.staff_editService_entry),
    path('staff_editService_entry_post/', views.staff_editService_entry_post),
    path('staff_ViewService_entry/', views.staff_ViewService_entry),
    path('staff_ViewService_entry_post/', views.staff_ViewService_entry_post),
    path('staff_addstock/<id>', views.staff_addstock),
    path('staff_addstockpost/', views.staff_addstockpost),
    path('staff_viewstock/<id>', views.staff_viewstock),

    #####################user
    path('user_signup/', views.user_signup),
    path('user_login/', views.user_login),
    path('user_view_profile/', views.user_view_profile),
    path('usr_send_complaint/', views.usr_send_complaint),
    path('usr_send_feedback/', views.usr_send_feedback),
    path('Cust_Send_reviews/', views.Cust_Send_reviews),
    path('user_edit_profile/', views.user_edit_profile),
    path('user_change_password/', views.user_change_password),
    path('user_view_doctors/', views.user_view_doctors),
    path('user_view_therapist/', views.user_view_therapist),
    path('user_view_doctorschedule/', views.user_view_doctorschedule),
    path('user_make_appointment/', views.user_make_appointment),
    path('user_view_appoinmentstatus/', views.user_view_appoinmentstatus),
    # path('user_view_reshedule_details/', views.user_view_reshedule_details),
    path('user_view_medical_history/', views.user_view_medical_history),
    path('user_view_service_history/', views.user_view_service_history),
    path('user_view_service_schedule_to_him_its_added_by_staff/', views.user_view_service_schedule_to_him_its_added_by_staff),
    path('user_view_service/', views.user_view_service),
    path('user_view_packages/', views.user_view_packages),
    path('usr_view_reply/', views.usr_view_reply),
]
